SGURestaurant/Controllers/MealsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SGURestaurant.Models;

namespace SGURestaurant.Controllers
{
    public class MealsController : Controller
    {
        private SGURestaurantContext db = new SGURestaurantContext();

        // GET: Meals
        public ActionResult Index()
        {
            var meals = db.Meals.Include(m => m.MealStyle).Include(m => m.MealType);
            return View(meals.ToList());
        }

        // GET: Meals/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Meal meal = db.Meals.Find(id);
            if (meal == null)
            {
                return HttpNotFound();
            }
            return View(meal);
        }

        // GET: Meals/Create
        public ActionResult Create()
        {
            ViewBag.MealStyleId = new SelectList(db.MealStyles, "Id", "Name");
            ViewBag.MealTypeId = new SelectList(db.MealTypes, "Id", "Name");
            return View();
        }

        // POST: Meals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Indredients,Price,MealTypeId,MealStyleId,ImageUrl,Status")] Meal meal)
        {
            if (ModelState.IsValid)
            {
                db.Meals.Add(meal);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MealStyleId = new SelectList(db.MealStyles, "Id", "Name", meal.MealStyleId);
            ViewBag.MealTypeId = new SelectList(db.MealTypes, "Id", "Name", meal.MealTypeId);
            return View(meal);
        }

        // GET: Meals/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Meal meal = db.Meals.Find(id);
            if (meal == null)
            {
                return HttpNotFound();
            }
            ViewBag.MealStyleId = new SelectList(db.MealStyles, "Id", "Name", meal.MealStyleId);
            ViewBag.MealTypeId = new SelectList(db.MealTypes, "Id", "Name", meal.MealTypeId);
            return View(meal);
        }

        // POST: Meals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Indredients,Price,MealTypeId,MealStyleId,ImageUrl,Status")] Meal meal)
        {
            if (ModelState.IsValid)
            {
                db.Entry(meal).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MealStyleId = new SelectList(db.MealStyles, "Id", "Name", meal.MealStyleId);
            ViewBag.MealTypeId = new SelectList(db.MealTypes, "Id", "Name", meal.MealTypeId);
            return View(meal);
        }

        // GET: Meals/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Meal meal = db.Meals.Find(id);
            if (meal == null)
            {
                return HttpNotFound();
            }
            return View(meal);
        }

        // POST: Meals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Meal meal = db.Meals.Find(id);
            db.Meals.Remove(meal);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SGURestaurant/Areas/Admin/Views/Shared/_404.cshtml
@{
    ViewBag.Title = "_404";
}

<h2>404 Not found!</h2>

SGURestaurant/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SGU Restaurant</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top nav-me">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Admin", "Index", "Admin", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Tổng quan", "Index", "Admin")</li>
                        <li>@Html.ActionLink("Quản lý người dùng", "Index", "Users")</li>
                    }
                    else if (User.IsInRole("Manager"))
                    {
                        <li>@Html.ActionLink("Quản lý món ăn", "Index", "Meals")</li>
                        <li>@Html.ActionLink("Quản lý đặt món", "Index", "Bookings")</li>
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @Html.Partial("_LoginPartial")
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @if (User.IsInRole("Admin") || User.IsInRole("Manager"))
        {
            @RenderBody();
        }
        else
        {
            @RenderPage("_404.cshtml", null);
        }   
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - SGU Restaurant</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>